/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "d.h"
/* Header for class arjunsuresh_webautomation_MainActivity */

#ifndef _Included_arjunsuresh_webautomation_MainActivity
#define _Included_arjunsuresh_webautomation_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arjunsuresh_webautomation_MainActivity
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arjunsuresh_webautomation_MainActivity_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
